language: python
sudo: false
python:
  - "3.6"

branches:
  only:
    - master

env:
  global:
    - secure: "anQLoxW+ZbwB97ePrEvR7CNEJlm97FkrQbnZmzTr9xjd9csv+pEfDbvA4eUKbokuAydE0CdJls9RZKUkwTiMVzIZitHcBP0atuZ4P5MhBG4aQS6c23uiKnoDz9z+JI3hJ30+djHMyV3cC67EP76Y9pDtSHf+ELanOswkE4sjZm5PG9fFH7PmmP2nHkILP0EL6W6ehC8nxFjf6nP/1SGbIXSwC8L+gccWgmuKzmknL2tOIBSkEj23+3yIIJ78WwAPhVcmaRfBZilUVx96/Bd5WHo5rfkhBIa3Hqv80MgrKBAj42dJ6XLGykz2sumcFpOOX+S1UOQoGMSqAEb05Z6znc1sV08AJK9iiY/qBJg5yiE/p4p3pMxL9VB2zrpVMcX5hsE5bFUE3Tr+mK6/DwyRXFH5KaPnMPuWHZZQMBZeIpwziv7WyKVvNKzBD666mgRF3ncyDQm7Bqiee9jiTisFG6GxKFpwlw0yBPgI1tFIUFPdZnHWYCOCrTtA/UlFZpP4Id37gduBopiNBrDZ4fO6eeKB50oYMbnED2IQY6HeU0x1kYVvLWZGqFYGNK7mfUX1EJYunnvdbIYTlOr2RPZJNCZXo61vFcZwKGKIIe5dK8+H2j+FKSrwoby6RJYp6dqKwLWc/10YQpzGXsC6WCXhCRupmJvOGw3TWEMiILFi8f8="

install:
  - pip install sphinx doctr

script:
  - |
    set -xe
    pushd docs
    make html
    popd

    # Maybe deploy documentation
    if [[ "$TRAVIS_BRANCH" == "master" && "$TRAVIS_EVENT_TYPE" == "push" ]]; then
        doctr deploy . --built-docs docs/build/html/
    fi

notifications:
  email: false
